### ISSUE TITLE
'dot' has a previous declaration as 'dotObj dot'

### ISSUE THREAD

**Issue by nathandarnell** [neu-rah/streamFlow#2]
I am on the latest version of streamFlow from 8/11/2019 and ArduinoMenu 4.17.26 and am getting this error in PlatformIO for streamFlow.h when compiling the serial example:

> 'dot' has a previous declaration as 'dotObj dot' [86, 15]
> conflicting declaration 'dotlObj dot' [87, 16]
> declaration is incompatible with "dotObj dot" (declared at line 86) [87, 16]

Lines 86-87 have: 
```
extern dotObj dot;
extern dotlObj dot;
```

and changing them to:
```
extern dotObj dot;
extern dotlObj dotl;
```

fixes the issue.  Is this just a typo or am I missing something?

**Comment by neu-rah** [comment]
guess its a typo, thanks for reporting it
